# -*- coding: utf-8 -*-
"""ScrappingDana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yUJq1rx-iwYPcNEtu4Z5QEoViVXGecAx
"""

!pip install google-play-scraper

from google_play_scraper import reviews_all, Sort
import csv

# Scraping data
scrapreview = reviews_all(
    'id.dana',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count=3000
)

# Save to CSV
with open('ulasan_apk.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['content'])
    for review in scrapreview:
        writer.writerow([review['content']])

print("Scraping selesai dan data disimpan sebagai ulasan_apk.csv")